"""empty message

Revision ID: 66425d9bae4b
Revises: 
Create Date: 2025-10-31 15:09:57.694196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66425d9bae4b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('files', sa.Text(), nullable=True),
    sa.Column('color', sa.Text(), nullable=True),
    sa.Column('shared', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('children_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['posts.id'], name=op.f('fk_posts_parent_id_posts'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_posts'))
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('sticky', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags')),
    sa.UniqueConstraint('name', name=op.f('uq_tags_name'))
    )
    op.create_table('tag_post_assoc',
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_tag_post_assoc_post_id_posts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_tag_post_assoc_tag_id_tags'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tag_id', 'post_id', name=op.f('pk_tag_post_assoc'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tag_post_assoc')
    op.drop_table('tags')
    op.drop_table('posts')
    # ### end Alembic commands ###
